---
- name: restart server
  shell: sleep 1 && /sbin/shutdown -r now
  async: true
  poll: false
  ignore_errors: true

- name: wait for server to be down
  delegate_to: localhost
  wait_for:
    state: stopped
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 10
    timeout: 60

- name: wait for server to boot
  delegate_to: localhost
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 10
    timeout: 300

- name: restart splunk
  service:
    name: splunk
    state: restarted
